language: python
python:
    - 2.7

env:
    - DEPS=true
    - DEPS=false

sudo: false

install:
    - travis_retry python setup.py install
    - travis_retry pip install coverage

script:
    - travis_retry python test_httpmultipart.py
    - travis_retry coverage erase
    - travis_retry coverage run test_httpmultipart.py
